name: generate snake animation

on:
  # run automatically every 24 hours
  schedule:
    - cron: "0 */12 * * *" 
  
  # allows to manually run the job at any time
  workflow_dispatch:
  
  # run on every push on the master branch
  push:
    branches:
    - master
    
jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      # checkout the repository content to get the README.md file
      - name: Checkout
        uses: actions/checkout@v3

      - name: generate snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/snake.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Move the generated SVG to the root directory
      - name: Move SVG to root
        run: mv dist/snake.svg snake.svg
          
      # push the content to the repository
      - name: push snake.svg to the repository
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Update snake.svg'
          add: 'snake.svg'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}