name: generate snake animation

on:
  # run automatically every 24 hours
  schedule:
    - cron: "0 */12 * * *" 
  
  # allows to manually run the job at any time
  workflow_dispatch:
  
  # run on every push on the master branch
  push:
    branches:
    - master
    
  

jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      # checkout the repository content to get the README.md file
      - name: Checkout
        uses: actions/checkout@v3

      # generates a snake game from a github user (<github_user_name>) contributions graph, output a svg animation at <svg_out_path>
      - name: generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            snake.svg
          snake_color: '#26a641'
          background_color: '#0d1117'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      # push the content to the repository
      - name: push snake.svg to the repository
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Update snake.svg'
          add: 'snake.svg'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
